# Generated by Django 3.2.25 on 2024-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default=' https://imgs.search.brave.com/IxO8vksofvQanAJ1nmPgkbF-u7rUWv7bnklGqS0JMGU/rs:fit:860:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzAxLzExLzAxLzA5/LzM2MF9GXzExMTAx/MDk0NV9LTjFyS2hQ/RnlYZDJzMlJXMk1t/M1lPQzFrRWRUUk9s/Yy5qcGc', max_length=500),
        ),
    ]
