# Generated by Django 3.2.25 on 2024-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default=' https://imgs.search.brave.com/DfARh4xce92UG7isvTGb8bf9TzobcfH3Z3Sbo8oy-24/rs:fit:860:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA3LzYxLzM5LzE4/LzM2MF9GXzc2MTM5/MTg1M19aWWZCc0V1/NDREZlJ1Wk5JaDJH/NVh2UVBkSExoTGZq/MS5qcGc', max_length=500),
        ),
    ]
